/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.ScheduleDAO;
import model.PlaceSchedule;
import model.Schedule;
import model.ServiceSchedule;
import model.Tour;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.Date;

/**
 *
 * @author vongn
 */
public class AddScheduleFrm extends javax.swing.JFrame {


    private Tour tour;
    private Schedule unsavedSchedule;
    /**
     * Creates new form AddSchedule
     */
    public AddScheduleFrm(Tour tour, Schedule unsavedSchedule) {
        initComponents();
        this.tour = tour;
        this.unsavedSchedule = unsavedSchedule;
        this.lblIdTour.setText(String.valueOf(tour.getId()));
        this.lblNameTour.setText(tour.getName());

        DefaultTableModel modelPlace = (DefaultTableModel) tblPlaceInfo.getModel();
        modelPlace.setRowCount(0);
        DefaultTableModel modelService = (DefaultTableModel) tblServiceInfo.getModel();
        modelService.setRowCount(0);

        if(unsavedSchedule.getListPlaceSchedule() != null) {
            for(PlaceSchedule placeSchedule : unsavedSchedule.getListPlaceSchedule()){
                modelPlace.addRow(new Object[]{
                        placeSchedule.getPlace().getName(),
                        placeSchedule.getPlace().getLocation(),
                        placeSchedule.getHourVisit(),
                        placeSchedule.getPlace().getDescription()
                });
                if(placeSchedule.getListServiceSchedule() != null) {
                    for(ServiceSchedule serviceSchedule : placeSchedule.getListServiceSchedule()){
                        modelService.addRow(new Object[]{
                                serviceSchedule.getServiceSupplier().getService().getName(),
                                serviceSchedule.getServiceSupplier().getType(),
                                serviceSchedule.getServiceSupplier().getPrice(),
                                serviceSchedule.getServiceSupplier().getSupplier().getName(),
                                placeSchedule.getPlace().getName(),
                                serviceSchedule.getQuantity()
                        });
                    }
                }

            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTicketPrice = new javax.swing.JTextField();
        txtDepartureDay = new javax.swing.JTextField();
        btnAddPlaces = new javax.swing.JButton();
        btnAddServices = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblServiceInfo = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPlaceInfo = new javax.swing.JTable();
        btnSave = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblNameTour = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblIdTour = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Add Schedule");

        jLabel2.setText("Ticket price:");

        jLabel3.setText("Departure day:");

        btnAddPlaces.setText("Add places");
        btnAddPlaces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPlacesActionPerformed(evt);
            }
        });

        btnAddServices.setText("Add services");
        btnAddServices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddServicesActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        tblServiceInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Type", "Price", "Supplier", "Place", "Quantity"
            }
        ));
        jScrollPane1.setViewportView(tblServiceInfo);

        tblPlaceInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Location", "Hours", "Description"
            }
        ));
        jScrollPane2.setViewportView(tblPlaceInfo);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Tour:");

        lblNameTour.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNameTour.setText("Ha Giang");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Id:");

        lblIdTour.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblIdTour.setText("001");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTicketPrice)
                                    .addComponent(txtDepartureDay, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(123, 123, 123)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnReset)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnSave)
                                        .addGap(73, 73, 73)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel6))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblIdTour)
                                            .addComponent(lblNameTour)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAddPlaces))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAddServices)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblIdTour))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTicketPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave)
                    .addComponent(jLabel4)
                    .addComponent(lblNameTour))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDepartureDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddPlaces)
                    .addComponent(btnAddServices))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        unsavedSchedule.setDepartureDay(new Date(txtDepartureDay.getText()));
        unsavedSchedule.setTicketPrice(Float.parseFloat(txtTicketPrice.getText()));
        ScheduleDAO scheduleDAO = new ScheduleDAO();
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to save this schedule?", "Confirm", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            if(scheduleDAO.addSchedule(tour, unsavedSchedule)) {
                JOptionPane.showMessageDialog(this, "Successfully saved schedule");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to save schedule");
            }
        }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        this.txtDepartureDay.setText("");
        this.txtTicketPrice.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnAddPlacesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPlacesActionPerformed
        // TODO add your handling code here:
        (new AddPlaceFrm(tour, unsavedSchedule)).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAddPlacesActionPerformed

    private void btnAddServicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddServicesActionPerformed
        // TODO add your handling code here:
        (new AddServicesFrm(tour, unsavedSchedule)).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAddServicesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddScheduleFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddScheduleFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddScheduleFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddScheduleFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddScheduleFrm(new Tour(), new Schedule()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPlaces;
    private javax.swing.JButton btnAddServices;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblIdTour;
    private javax.swing.JLabel lblNameTour;
    private javax.swing.JTable tblPlaceInfo;
    private javax.swing.JTable tblServiceInfo;
    private javax.swing.JTextField txtDepartureDay;
    private javax.swing.JTextField txtTicketPrice;
    // End of variables declaration//GEN-END:variables
}
