/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.ServiceSupplierDAO;
import model.*;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;

/**
 *
 * @author vongn
 */
public class ChooseSupplierFrm extends javax.swing.JFrame {

    private Tour tour;
    private Schedule unsavedSchedule;
    private Service selectedService;
    /**
     * Creates new form ChooseSupplier
     */
    public ChooseSupplierFrm(Tour tour, Schedule unsavedSchedule ,Service selectedService) {

        initComponents();
        this.selectedService = selectedService;
        this.tour = tour;
        this.unsavedSchedule = unsavedSchedule;

        this.cbPlace.removeAllItems();
        for (PlaceSchedule placeSchedule: unsavedSchedule.getListPlaceSchedule()) {
            cbPlace.addItem(placeSchedule);
        }

        ServiceSupplierDAO serviceSupplierDAO = new ServiceSupplierDAO();
        List<ServiceSupplier> serviceSuppliers = serviceSupplierDAO.getAllServiceSupplierByService(selectedService);
        DefaultTableModel model = (DefaultTableModel) tblResult.getModel();
        model.setRowCount(0);
        for (ServiceSupplier serviceSupplier: serviceSuppliers) {
            Supplier supplier = serviceSupplier.getSupplier();
            model.addRow(new Object[] {
                    serviceSupplier.getId(),
                    supplier.getName(),
                    supplier.getEmail(),
                    supplier.getTel(),
                    serviceSupplier.getType(),
                    serviceSupplier.getPrice(),
                    supplier.getNote()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResult = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        cbPlace = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Choose Supplier");

        tblResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Email", "Telephone", "Type", "Price", "Note"
            }
        ));
        tblResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblResultMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblResult);

        jLabel2.setText("Use in place:");

        cbPlace.setModel(new javax.swing.DefaultComboBoxModel<>(new PlaceSchedule[] { }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(343, 343, 343)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(cbPlace, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbPlace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblResultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblResultMouseClicked
        // TODO add your handling code here:
        ServiceSupplier selectedServiceSupplier = new ServiceSupplier();
        int row = tblResult.getSelectedRow();
        selectedServiceSupplier.setId((int) tblResult.getValueAt(row, 0));
        selectedServiceSupplier.setType((String) tblResult.getValueAt(row, 4));
        selectedServiceSupplier.setPrice((int) tblResult.getValueAt(row, 5));
        Supplier supplier = new Supplier();
        supplier.setName((String) tblResult.getValueAt(row, 1));
        supplier.setEmail((String) tblResult.getValueAt(row, 2));
        supplier.setTel((String) tblResult.getValueAt(row, 3));
        supplier.setNote((String) tblResult.getValueAt(row, 6));
        selectedServiceSupplier.setSupplier(supplier);
        selectedServiceSupplier.setService(selectedService);

        String quantity = JOptionPane.showInputDialog("Enter the quantity:");
        if (quantity != null && !quantity.isEmpty()) {
            int quantityInt = Integer.parseInt(quantity);
            PlaceSchedule selectedPlaceSchedule = (PlaceSchedule) cbPlace.getSelectedItem();
            PlaceSchedule existingPlaceSchedule = unsavedSchedule.getListPlaceSchedule().stream()
                    .filter(placeSchedule -> placeSchedule.equals(selectedPlaceSchedule))
                    .findFirst()
                    .orElse(null);

            ServiceSchedule serviceSchedule = new ServiceSchedule();
            serviceSchedule.setServiceSupplier(selectedServiceSupplier);
            serviceSchedule.setQuantity(quantityInt);
            serviceSchedule.setPrice(selectedServiceSupplier.getPrice());
            existingPlaceSchedule.getListServiceSchedule().add(serviceSchedule);

            (new AddServicesFrm(tour, unsavedSchedule)).setVisible(true);
            this.dispose();
        }
        else {
            JOptionPane.showMessageDialog(this, "Please enter the quantity");
        }
    }//GEN-LAST:event_tblResultMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChooseSupplierFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChooseSupplierFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChooseSupplierFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChooseSupplierFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChooseSupplierFrm(new Tour(), new Schedule(),new Service()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<PlaceSchedule> cbPlace;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblResult;
    // End of variables declaration//GEN-END:variables
}
